### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by motuko61** [motuko61/furima-35954#9]
# URL |  https://furima-35954.herokuapp.com/
# Basic認証のIDとパスワード |  admin, 2222
# 出品者用のメールアドレスとパスワード | tama@gmail.com, tama111
# 購入者用のメールアドレスとパスワード |kuma@com,  kuma111

**Comment by takumi0530** [comment]
@motuko61 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **エラーハンドリングの際、1つのエラーに対して同じエラーメッセージが重複して表示されないこと（出品・編集）**
「Price is invalid」の記述が重複していました。
<img width="167" alt="スクリーンショット 2021-07-08 17 03 52" src="https://user-images.githubusercontent.com/76197191/124885749-8d511f80-e00e-11eb-9ae7-c2779e43b64c.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by motuko61** [comment]
修正完了しました。確認お願いします！

**Comment by takumi0530** [comment]
@motuko61 さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/124891114-a4464080-e013-11eb-8731-1802e458f069.png)
